branch-defaults:
  dev:
    environment: udagram-dev-env
    group_suffix: null
  f-auth:
    environment: udagram-dev-dev
global:
  application_name: udagram-dev
  branch: null
  default_ec2_keyname: udagram-media
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
